// @ts-nocheck
import * as __fd_glob_53 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/guides/icons.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/guides/getting-started.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/guides/changelog.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/foundations/typography.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/foundations/spacing.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/foundations/shadows.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/foundations/radius.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/foundations/index.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/foundations/heights.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/foundations/grid.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/foundations/corner-smoothing.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/foundations/colors.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/foundations/borders.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/toggle.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/toast.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/text-field.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/table.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/status-chips.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/snackbar.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/slider.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/side-panel.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/segmented-control.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/search-bar.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/radio-button.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/progress-bar.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/pagination.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/otp-input.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/index.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/dropdown.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/divider.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/date-picker.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/container.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/chip.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/buttons.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/breadcrumbs.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/bottom-sheet.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/foundations/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "components/meta.json": __fd_glob_1, "foundations/meta.json": __fd_glob_2, "guides/meta.json": __fd_glob_3, }, {"index.mdx": __fd_glob_4, "components/accordion.mdx": __fd_glob_5, "components/alert.mdx": __fd_glob_6, "components/avatar.mdx": __fd_glob_7, "components/badge.mdx": __fd_glob_8, "components/bottom-sheet.mdx": __fd_glob_9, "components/breadcrumbs.mdx": __fd_glob_10, "components/buttons.mdx": __fd_glob_11, "components/card.mdx": __fd_glob_12, "components/checkbox.mdx": __fd_glob_13, "components/chip.mdx": __fd_glob_14, "components/container.mdx": __fd_glob_15, "components/date-picker.mdx": __fd_glob_16, "components/dialog.mdx": __fd_glob_17, "components/divider.mdx": __fd_glob_18, "components/dropdown.mdx": __fd_glob_19, "components/index.mdx": __fd_glob_20, "components/otp-input.mdx": __fd_glob_21, "components/pagination.mdx": __fd_glob_22, "components/popover.mdx": __fd_glob_23, "components/progress-bar.mdx": __fd_glob_24, "components/radio-button.mdx": __fd_glob_25, "components/search-bar.mdx": __fd_glob_26, "components/segmented-control.mdx": __fd_glob_27, "components/select.mdx": __fd_glob_28, "components/side-panel.mdx": __fd_glob_29, "components/skeleton.mdx": __fd_glob_30, "components/slider.mdx": __fd_glob_31, "components/snackbar.mdx": __fd_glob_32, "components/status-chips.mdx": __fd_glob_33, "components/table.mdx": __fd_glob_34, "components/tabs.mdx": __fd_glob_35, "components/text-field.mdx": __fd_glob_36, "components/toast.mdx": __fd_glob_37, "components/toggle.mdx": __fd_glob_38, "components/tooltip.mdx": __fd_glob_39, "foundations/borders.mdx": __fd_glob_40, "foundations/colors.mdx": __fd_glob_41, "foundations/corner-smoothing.mdx": __fd_glob_42, "foundations/grid.mdx": __fd_glob_43, "foundations/heights.mdx": __fd_glob_44, "foundations/index.mdx": __fd_glob_45, "foundations/radius.mdx": __fd_glob_46, "foundations/shadows.mdx": __fd_glob_47, "foundations/spacing.mdx": __fd_glob_48, "foundations/typography.mdx": __fd_glob_49, "guides/changelog.mdx": __fd_glob_50, "guides/getting-started.mdx": __fd_glob_51, "guides/icons.mdx": __fd_glob_52, "guides/index.mdx": __fd_glob_53, });